# Namespace Definition
apiVersion: v1
kind: Namespace
metadata:
  name: pacman-argo

---

# Ingress Definition
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pacman-argo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: pacman-argo.paxel.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pac-man
                port:
                  number: 8080
  tls:
    - hosts:
        - pacman-argo.paxel.ca
      secretName: pacman-argo.paxel.ca-tls

---

# Ingress Definition
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pacman-argo-test-2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: "pacman-argo-2.paxel.ca."
    external-dns.alpha.kubernetes.io/target: "router.paxel.ca."
    external-dns.alpha.kubernetes.io/type: "CNAME"
spec:
  ingressClassName: nginx
  rules:
    - host: pacman-argo-2.paxel.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pac-man
                port:
                  number: 8080
  tls:
    - hosts:
        - pacman-argo-2.paxel.ca
      secretName: pacman-argo-2.paxel.ca-tls
---

# Service Definition for Pac-Man Application
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "pacman-argo-2.paxel.ca."
    external-dns.alpha.kubernetes.io/target: "router.paxel.ca."
    external-dns.alpha.kubernetes.io/type: "CNAME"
  name: pac-man
  namespace: pacman-argo
  labels:
    name: pac-man
spec:
  selector:
    name: pac-man
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

# Deployment Definition for Pac-Man Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pac-man
  namespace: pacman-argo
  labels:
    name: pac-man
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pac-man
  template:
    metadata:
      labels:
        name: pac-man
    spec:
      containers:
        - name: pac-man
          image: docker.io/jessehoch/pacman-nodejs-app:latest
          ports:
            - name: http-server
              containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: MONGO_SERVICE_HOST
              value: "mongo.pacman-argo.svc.cluster.local"
            - name: MONGO_AUTH_USER
              value: "pacman"
            - name: MONGO_AUTH_PWD
              value: "pacman"
            - name: MONGO_DATABASE
              value: "pacman"
            - name: MONGO_COLLECTION 
              value: "pacman"
            # Additional environment variables can be added here as required
