apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pacman-argo.paxel.ca
  namespace: pacman-argo
spec:
  secretName: pacman-argo.paxel.ca-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pacman-argo.paxel.ca
  dnsNames:
  - pacman-argo.paxel.ca